"""empty message

Revision ID: f41fa13970fc
Revises: 2c2cd6ce53a4
Create Date: 2021-05-25 17:40:29.985129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41fa13970fc'
down_revision = '2c2cd6ce53a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
